server:
  host: "0.0.0.0"
  port: 8000
  read_timeout: 5s
  write_timeout: 5s

database:
  host: "db"
  port: 5432
  user: "people"
  password: "people"
  dbname: "people_enricher"
  sslmode: "disable"

log:
  level: "info"

enrichment:
  timeout: 2s
  retry: 2